name: Bitfinex
on:
  schedule:
    - cron:  '2 0 * * *'
jobs:
  build:
    name: Bitfinex tickers
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v2

      - run: python3 bitfinex/pairs.py -m -q BTC> bitfinex/bitfinex_BTC_margin.txt
      - run: python3 bitfinex/pairs.py -m -q USD> bitfinex/bitfinex_USD_margin.txt
      - run: python3 bitfinex/pairs.py -m > bitfinex/bitfinex_margin_pairs.txt
      - run: python3 bitfinex/pairs.py -q BTC > bitfinex/bitfinex_BTC_pairs.txt
      - run: python3 bitfinex/pairs.py -q USD > bitfinex/bitfinex_USD_pairs.txt
      - run: python3 bitfinex/pairs.py > bitfinex/bitfinex_all_pairs.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bitfinex/
          git diff-index --quiet HEAD || git commit -m "Bitfinex: automatic update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}