name: FTX
on:
  schedule:
    - cron:  '6 0 * * *'
jobs:
  build:
    name: FTX tickers
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v2

      - run: python3 ftx/pairs.py -s > ftx/ftx_spot_pairs.txt
      - run: python3 ftx/pairs.py -f > ftx/ftx_futures_pairs.txt
      - run: python3 ftx/pairs.py > ftx/ftx_all_pairs.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ftx/
          git diff-index --quiet HEAD || git commit -m "FTX: automatic update" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}